name: Build & Deploy
on:
  push:
    branches: [master]

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Deploy NodeJS app
        uses: appleboy/ssh-action@v0.1.2
        with:
          host: ${{secrets.SSH_HOST}} # IP address of the server you wish to ssh into
          key: ${{secrets.SSH_KEY}} # Private or public key of the server
          username: ${{ secrets.SSH_USERNAME }} # User of the server you want to ssh into
          passphrase: ${{ secrets.SSH_KEY_PASS }}
          
          script: |
                echo 'Starting CI/CD'
                cd ~
                rm -rf monoApp
                git clone https://github.com/etopeojo/monoApp.git
                ls -l
                cd monoApp/
                cd webSocketServer/
                npm install
                pm2 startOrRestart ecosystem.config.js
                cd ../
                cd bankServiceApi
                ln -sfn ~/env/.env ./.env
                npm install
                pm2 startOrRestart ecosystem.config.js
                echo 'Deployment successful'
